INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (4, 'Samsung Galaxy S25', 'SMS-S25', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (5, 'Samsung Galaxy A56', 'SMS-A56', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (6, 'Xiaomi 15', 'XIA-15', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (7, 'Redmi Note 14 Pro', 'RED-N14P', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (8, 'AirPods 4', 'APL-AP4', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (9, 'Apple Watch Series 10', 'APL-AW10', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (10, 'Galaxy Watch Ultra', 'SMS-GWU', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (11, 'iPad Air M3', 'APL-IPADM3', 'Tablet');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (12, 'Galaxy Tab S10', 'SMS-TABS10', 'Tablet');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (13, 'Turkcell Superbox', 'TCL-SBOX', 'Modem');

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (4, 1, 7);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (4, 5, 2);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (5, 3, 9);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (6, 8, 4);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (7, 10, 6);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (8, 2, 3);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (9, 11, 5);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (10, 15, 1);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (11, 6, 8);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (12, 9, 0);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY)
VALUES (13, 4, 10);

COMMIT;