INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (1, 'iPhone 15 128GB', 'APL-IPH15-128', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (2, 'iPhone 15 Pro 256GB', 'APL-IPH15P-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (3, 'Samsung Galaxy S24 Ultra', 'SAM-S24U-512', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (4, 'Samsung Galaxy A55 128GB', 'SAM-A55-128', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (5, 'AirPods Pro Gen 2', 'APL-APP2', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (6, 'Apple Watch Series 9', 'APL-AW9-45', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (7, 'Samsung Galaxy Watch 6', 'SAM-GW6-44', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (8, 'Xiaomi Redmi Note 13', 'XIA-RN13-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (9, 'Turkcell Superbox Router', 'TKC-SBOX-LTE', 'Network');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (10, 'Anker PowerCore 20k', 'ANK-PC20', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (11, 'iPad Air M3', 'APL-IPADAIR-M3', 'Tablets');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (12, 'Samsung Galaxy Tab S10', 'SAM-TABS10', 'Tablets');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (13, 'Turkcell Superbox 5G', 'TKC-SBOX-5G', 'Network');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (14, 'Xiaomi 15', 'XIA-15-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (15, 'Samsung Galaxy S25', 'SAM-S25-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (16, 'JBL Tune 770NC', 'JBL-T770NC', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (17, 'Apple Pencil Pro', 'APL-PENCIL-PRO', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (18, 'Samsung Galaxy Buds3 Pro', 'SAM-BUDS3-PRO', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (19, 'Huawei Watch GT 5', 'HUA-WGT5', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (20, 'TP-Link Archer AX55', 'TPL-AX55', 'Network');

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 1, 10);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 2, 4);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 3, 0);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 4, 7);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 5, 3);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 7, 12);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 8, 2);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (1, 12, 0);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (2, 1, 6);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (2, 2, 1);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (2, 3, 8);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (2, 6, 3);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (2, 9, 0);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (3, 1, 3);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (3, 2, 12);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (3, 3, 0);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (3, 5, 5);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (3, 10, 2);

INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 1, 20);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 2, 15);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 3, 18);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 4, 25);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 5, 8);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 6, 30);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 7, 5);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 8, 2);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 9, 0);
INSERT INTO STOCK (PRODUCT_ID, STORE_ID, QUANTITY) VALUES (5, 10, 12);

COMMIT;
