ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = stock_app;

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (1, 'iPhone 15 128GB', 'APL-IPH15-128', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (2, 'iPhone 15 Pro 256GB', 'APL-IPH15P-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (3, 'Samsung Galaxy S24 Ultra', 'SAM-S24U-512', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (4, 'Samsung Galaxy A55 128GB', 'SAM-A55-128', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (5, 'AirPods Pro Gen 2', 'APL-APP2', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (6, 'Apple Watch Series 9', 'APL-AW9-45', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (7, 'Samsung Galaxy Watch 6', 'SAM-GW6-44', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (8, 'Xiaomi Redmi Note 13', 'XIA-RN13-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (9, 'Turkcell Superbox Router', 'TKC-SBOX-LTE', 'Network');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (10, 'Anker PowerCore 20k', 'ANK-PC20', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (11, 'iPad Air M3', 'APL-IPADAIR-M3', 'Tablets');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (12, 'Samsung Galaxy Tab S10', 'SAM-TABS10', 'Tablets');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (13, 'Turkcell Superbox 5G', 'TKC-SBOX-5G', 'Network');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (14, 'Xiaomi 15', 'XIA-15-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (15, 'Samsung Galaxy S25', 'SAM-S25-256', 'Smartphones');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (16, 'JBL Tune 770NC', 'JBL-T770NC', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (17, 'Apple Pencil Pro', 'APL-PENCIL-PRO', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (18, 'Samsung Galaxy Buds3 Pro', 'SAM-BUDS3-PRO', 'Accessories');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (19, 'Huawei Watch GT 5', 'HUA-WGT5', 'Wearables');

INSERT INTO PRODUCT (ID, NAME, SKU, CATEGORY)
VALUES (20, 'TP-Link Archer AX55', 'TPL-AX55', 'Network');

COMMIT;
